### ISSUE TITLE
Enhancement Request: Add ability to run elasticbeat in a docker container

### ISSUE THREAD

**Issue by ericslandry** [radoondas/elasticbeat#35]
I'd love to see this beat be docker-able like:
https://github.com/Ingensi/dockbeat

**Comment by ericslandry** [comment]
I got it to work by following dockbeat pattern and adding 2 files - Dockerfile and elasticbeat-docker.yml. Not sure how to do a clean PR cause of docker namespacing issues, but here's the quick and dirty (I'm sure these files could be cleaned up a lot).

**Dockerfile:**
```
FROM golang:1.7

# install pyyaml
RUN cd /tmp && wget http://pyyaml.org/download/pyyaml/PyYAML-3.11.tar.gz && tar -zxvf PyYAML-3.11.tar.gz
RUN cd /tmp/PyYAML-3.11 && python setup.py install
# install glide
RUN go get github.com/Masterminds/glide

COPY . $GOPATH/src/github.com/radoondas/elasticbeat
RUN cd $GOPATH/src/github.com/radoondas/elasticbeat && make && make

RUN mkdir -p /etc/elasticbeat/ \
    && cp $GOPATH/src/github.com/radoondas/elasticbeat/elasticbeat /usr/local/bin/elasticbeat \
    && cp $GOPATH/src/github.com/radoondas/elasticbeat/elasticbeat-docker.yml /etc/elasticbeat/elasticbeat.yml \
    && cp $GOPATH/src/github.com/radoondas/elasticbeat/etc/elasticbeat.template.json /etc/elasticbeat/

WORKDIR /etc/elasticbeat
ENTRYPOINT elasticbeat

CMD [ "-c", "elasticbeat.yml", "-e" ]

```

**elasticbeat-docker.yml**
```
input:
  period: ${ELASTICBEAT_PERIOD:10} 
  urls:
    - http://${ELASTICBEAT_URL:127.0.0.1:9200}
  stats:
    cluster: ${ELASTICBEAT_CLUSTER:true}
    nodes: ${ELASTICBEAT_NODES:true}
    health: ${ELASTICBEAT_HEALTH:true}
output:
  elasticsearch:
    hosts: ["${ELASTICBEAT_URL:localhost:9200}"]
    template:
      name: "elasticbeat"
      path: "elasticbeat.template.json"
      overwrite: false
shipper:
logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
```

Then a few docker cmds:
- docker build -t elasticbeat .
- docker run -e ELASTICBEAT_URL='192.168.1.2:9200' elasticbeat
